name: CI
on:
  push:
    branches:
    - main
jobs:
  split-upm:
    name: split upm branch (force)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: split upm branch
      run: |
        git branch -d upm &> /dev/null || echo upm branch not found
        git subtree split -P "$PKG_ROOT" -b upm
        git checkout upm
        if [[ -d "Samples" ]]; then
          git mv Samples Samples~
          rm -f Samples.meta
          git config --global user.name 'github-bot'
          git config --global user.email 'github-bot@users.noreply.github.com'
          git commit -am "fix: Samples => Samples~"
        fi
        if [[ -d "Documentation" ]]; then
          git mv Documentation Documentation~
          rm -f Documentation.meta
          git config --global user.name 'github-bot'
          git config --global user.email 'github-bot@users.noreply.github.com'
          git commit -am "fix: Documentation => Documentation~"
        fi
        git push -f -u origin upm
        git checkout main
        git ls-files
        git checkout upm ./README.md
        git commit -am "Copy README.md to upm branch"
        git push origin upm
      env:
        PKG_ROOT: Packages/com.kevincastejon.missingfeatures
